version: "3.3"
services:
  sensor:
    build: ./Sensor
    environment:
      - SENSOR_SERVICE_ADDRESS=http://controller:8087/data
    deploy:
      replicas: 8
  controller:
    build: ./Controller
    ports:
      - "8087:8087"
  manipulator:
    build: ./Manipulator
    ports:
      - "8088:8088"
